
name: Blog posts on ReadMe
on:
  schedule:
    # Runs every day at 8am UTC
    - cron: '5 * * * *'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: http://jasonkuehl.com/sitemap-files/htm/posts/post/1/
          count: 10
      - name: Commit file changes
        run: |
            git config --global user.name 'Jason Kuehl'
            git config --global user.email 'jason@jasonkuehl.com'
            git add .
            git diff --quiet --cached || git commit -m "Adding update to blog" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
